name: CMake

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check_tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        tasks:
          [
            Task0,
            Task1,
            Task2,
            Task3,
            Task4,
          ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ${{github.workspace}}/${{ matrix.test-group }}/build -S ${{github.workspace}}/${{ matrix.test-group }}

    - name: Build
      run: cmake --build ${{github.workspace}}/${{ matrix.test-group }}/build

    - name: Test
      working-directory: ${{github.workspace}}/${{ matrix.test-group }}/build
      run: ctest --extra-verbose

