name: CMake

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  check_tasks:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        tasks: [ Task0, Task1, Task2, Task3, Task4 ]

    steps:
    - uses: actions/checkout@v3

    - name: Configure
      run: cmake -B ./${{ matrix.tasks }}/build -S ./${{ matrix.tasks }}

    - name: Build
      run: cmake --build ./${{ matrix.tasks }}/build

    - name: Test
      working-directory: ./${{ matrix.tasks }}/build
      run: ctest --extra-verbose

